Manulife.WebApp/Manulife.WebApp/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace Manulife.WebApp.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

Manulife.WebApp/Manulife.WebApp/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Manulife.WebApp.Areas.HelpPage.Models;

namespace Manulife.WebApp.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

Manulife.WebApp/Manulife.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Manulife.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Manulife.WebApp/Manulife.WebApp/Controllers/RankSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Application.Repository;
using Application.Repository.Models;
using Newtonsoft.Json;

namespace Manulife.WebApp.Controllers
{
    public class RankSearchController : ApiController
    {
        DataRepository _repository = new DataRepository();

        [HttpGet]
        public IEnumerable<SiteRankingModel> Get(string sorder, string search)
        {
            var searchCriteria = JsonConvert.DeserializeObject<SearchModel>(search);

            if (searchCriteria == null)
                searchCriteria = new SearchModel();
            else
            {
                if (searchCriteria.dateFrom != null)
                {
                    //fix for html5 subtracting 1 day from the selected date
                    searchCriteria.dateFrom = searchCriteria.dateFrom.Value.AddDays(1);
                    searchCriteria.dateFrom = new DateTime(searchCriteria.dateFrom.Value.Date.Year, searchCriteria.dateFrom.Value.Date.Month,
                                                                searchCriteria.dateFrom.Value.Date.Day, 0, 0, 0);
                }
                if (searchCriteria.dateTo != null)
                {
                    //fix for html5 subtracting 1 day from the selected date
                    searchCriteria.dateTo = searchCriteria.dateTo.Value.AddDays(1);
                    searchCriteria.dateTo = new DateTime(searchCriteria.dateTo.Value.Date.Year, searchCriteria.dateTo.Value.Date.Month,
                                                                searchCriteria.dateTo.Value.Date.Day, 23, 59, 0);
                }
            }

            return _repository.GetandFilter(searchCriteria, sorder);
        }

    }
}

Manulife.WebApp/Manulife.WebApp/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Manulife.WebApp.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

Manulife.WebApp/Manulife.WebApp/Views/Home/Index.cshtml
<div class="col-md-12 appBody" data-ng-controller="SiteSearchController">
    <div class="loader-container" data-ng-show="loading">
        <div class="loader"></div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>Site Rank Search Criteria</h4>
        </div>
        <div class="panel-body">
            <div class="form form-horizontal">
                <div class="form-group">
                    <label for="siteName" class="col-md-3 control-label">Website URL/Name</label>
                    <div class="col-md-4">
                        <input type="text" id="siteName" class="form-control" data-ng-model="searchModel.siteName"
                            placeholder="www.example.com or example"
                            data-ng-keyup="$event.keyCode == 13 && searchRanking()" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="dateFrom" class="col-md-3 control-label">Date From</label>
                    <div class="col-md-2">
                        <input type="date" id="dateFrom" class="form-control" data-ng-model="searchModel.dateFrom" data-ng-keyup="$event.keyCode == 13 && searchRanking()" />
                    </div>
                    <label for="dateTo" class="col-md-2 control-label">Date To</label>
                    <div class="col-md-2">
                        <input type="date" id="dateTo" class="form-control" data-ng-model="searchModel.dateTo" data-ng-keyup="$event.keyCode == 13 && searchRanking()" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="reportType" class="col-md-3 control-label">Top Sites (based on visits)</label>
                    <div class="col-md-2">
                        <select id="reportType" class="form-control" data-ng-model="searchModel.type" data-ng-change="searchRanking()">
                            <option value="0" selected>All</option>
                            <option value="5">Top 5</option>
                            <option value="10">Top 10</option>
                            <option value="30">Top 30</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">&nbsp;</div>
                    <div class="col-md-5">
                        <input type="button" class="btn btn-primary" id="btnSearch" value="Search" data-ng-click="searchRanking()" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="input-group" style="width: 9%;">
        <span class="glyphicon glyphicon-th-list input-group-addon"></span>
        <select id="tablePageSize" class="form-control" data-ng-model="pageSize" data-ng-change="numberOfPages()">
            <option value="5" selected>5</option>
            <option value="10">10</option>
            <option value="20">20</option>
        </select>
    </div>

    <div class="result">
        <table id="resultTable" class="table table-striped table-condensed">
            <colgroup>
                <col style="width: 10%;" />
                <col style="width: 40%;" />
                <col style="width: 25%;" />
                <col style="width: 25%;" />
            </colgroup>
            <thead class="resultHeader">
                <tr >
                    <th>Rank</th>
                    <th>Website</th>
                    <th>No. of Visits <span data-ng-class="{'glyphicon glyphicon-chevron-down': ranking == 'down', 'glyphicon glyphicon-chevron-up': ranking =='up'}"
                        data-ng-click="changeRanking()"></span>
                    </th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                <tr data-ng-repeat="site in sites | 
                                    pagination: curPage * pageSize | limitTo: pageSize">
                    <td>{{site.rank}}</td>
                    <td>{{site.siteName}}</td>
                    <td>{{site.visits | number}}</td>
                    <td>{{site.date}}</td>
                </tr>
            </tbody>
            <tr data-ng-show="sites.length <= 0">
                <td colspan="2">No records to show.</td>
            </tr>
            <tr>
                <td colspan="4">
                    <nav style="text-align:center;" data-ng-show="sites.length">
                        <ul class="pager">
                            <li>
                                <input type="button" class="btn btn-primary" data-ng-disabled="curPage == 0"
                                    data-ng-click="curPage=curPage-1" value="&lt; Previous"/>
                            </li>
                            <li id="pageInfo">
                                <span>Page {{curPage + 1}} of {{ numberOfPages() }}</span>
                            </li>
                            <li>
                                <input type="button" class="btn btn-primary"
                                    data-ng-disabled="curPage >= sites.length/pageSize - 1"
                                    data-ng-click="curPage = curPage+1" value="Next &gt;" />
                            </li>
                        </ul>
                    </nav>
                </td>
            </tr>
        </table>
    </div>
</div>

<script>
    $(function () {
        $('#reportType').val(0);
        $('#tablePageSize').val(5);
    });
</script>

Manulife.WebApp/Manulife.WebApp/Views/Shared/_Layout.cshtml
@{
    ViewBag.SiteTitle = "Site Rank Search Application: Herbert Fabillar";
}
<!DOCTYPE html>
<html ng-app="siteRankApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.SiteTitle</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")

    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Content/themes/base/css")*@

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>*@
    @RenderBody()

    
    
    @RenderSection("scripts", required: false)
</body>
</html>